meta-data:
  repository_name: regression-monkey-julia-mathcamp
  visibility: public
  org-name: RyoNakagami
  tag:
    - blog
    - Julia
    - mathcamp
  description: |
    Code repository for Regression Monkey MathCamp in Julia blog post
  homepage: https://ryonakagami.github.io/regression-monkey-julia-mathcamp/
  license: mit
